# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

commands:
  run_test:
    steps:
      - checkout

      - run:
          name: Setup Google credentials
          command: |
            echo ${GOOGLE_SERVICE_CREDENTIALS} > ${HOME}/gcp-credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-credentials.json' >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run:
          name: Running tests
          command: yarn test

jobs:
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - run_test
  node11:
    docker:
      - image: circleci/node:11
    steps:
      - run_test
  node12:
    docker:
      - image: circleci/node:12
    steps:
      - run_test
  node13:
    docker:
      - image: circleci/node:13
    steps:
      - run_test

workflows:
  version: 2
  test:
    jobs:
      - node10
      - node11
      - node12
      - node13
